# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# need to limit 4million
limit = 4000000

# a +  = c -> b + C = d
# 1st variable could start at 0 and total would be 0 and it'll give the same result
firstnu = 1
secondnu = 2
fibnum = firstnu + secondnu
total = 2

# Create the fibonacce sum - thinking loop or recusive code block
    # Find the sum of the even valued terms

while (fibnum <= limit):
    # even number total
    if fibnum % 2 == 0:
        total += fibnum
    # test
    print(fibnum)

    # change the above variables
    firstnu = secondnu
    secondnu = fibnum
    fibnum = firstnu + secondnu

# total should be 4613732
print(f"total: {total}")

