-- shift+ctrl+p = add new connection & use url, database, user & password from sheet
-- shift+ctrl+e = execute
select name 
from sys.databases

-- SELECT '104153018' as studentid, *

USE ATDB;

-- Q1:
SELECT '104153018' as studentid, *
FROM BOOKING
WHERE EVENTYEAR = '2021'
ORDER BY EVENTMONTH ASC, EVENTDAY ASC
;

-- Q2:
SELECT '104153018' as studentid, E.TOURNAME, C.GENDER, COUNT(B.DATEBOOKED) AS NUM_BOOKINGS
FROM BOOKING AS B
INNER JOIN CLIENT AS C ON B.CLIENTID = C.CLIENTID
INNER JOIN EVENT AS E ON B.TOURNAME = E.TOURNAME
GROUP BY C.GENDER, COUNT(B.DATEBOOKED), B.TOURNAME
;

-- Q3:
SELECT '104153018' as studentid, E.TOURNAME, C.GENDER, COUNT(B.DATEBOOKED) AS NUM_BOOKINGS
FROM EVENT AS E
INNER JOIN BOOKING AS E ON E.TOURNAME = B.TOURNAME
INNER JOIN CLIENT AS C ON B.CLIENTID = C.CLIENTID
GROUP BY C.GENDER, COUNT(B.DATEBOOKED), B.TOURNAME
HAVING B.EVENTMONTH > 2
ORDER BY B.TOURNAME
;

-- Q4:

-- Q5:

-- Q6:

-- Q7:

-- Q8:

-- Q9:

-- Q10:


