use kayhoweDB;

-- SELECT TOP(10) MOVIENO, TITLE, RELYEAR, RUNTIME, RATINGCODE, COLOURCODE, TMDB_SCORE, TMDB_VOTES, TMDB_ID
-- FROM MOVIE3018;

SELECT TOP(5) *
FROM MOVIE3018
WHERE RUNTIME > (SELECT AVG(RUNTIME) FROM MOVIE3018)
;

SELECT *
FROM MOVIE3018
WHERE RUNTIME = (SELECT MAX(RUNTIME) FROM MOVIE3018)
;

SELECT M.TITLE, M.RELYEAR, A.FULLNAME, A.BIRTHCOUNTRY
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
WHERE A.ACTORNO IN (SELECT A.ACTORNO FROM ACTOR3018 WHERE BIRTHCOUNTRY = 'Australia' OR A.BIRTHCOUNTRY = 'England')
; --WASTING MY TIME, PYTHON IS KILLING ALL THE BUNNIES WITH HERPIES 
