-- shift+ctrl+p = add new connection & use url, database, user & password from sheet
-- shift+ctrl+e = execute
select name 
from sys.databases

-- Show all tables IN DATABASE:
SELECT *
FROM information_schema.tables;

SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE='BASE TABLE';

-- create database kayhoweDB;

-- USE kayhoweDB;

USE ATDB;

SELECT '104153018' as studentid, *
FROM MOVIE
WHERE RELYEAR = 2003
ORDER BY RATINGCODE, TMDB_SCORE ASC
;

SELECT '104153018' as studentid, M.TITLE AS MOVIE_NAME, A.GENDER, COUNT(A.GENDER) AS NUM_ROLES
FROM MOVIE AS M
INNER JOIN CASTING AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR AS A ON C.ACTORNO = A.ACTORNO
GROUP BY M.TITLE, M.RELYEAR, A.GENDER
HAVING M.RELYEAR = 2001
ORDER BY M.TITLE DESC, A.GENDER
;

SELECT '104153018' as studentid, M.TITLE AS MOVIE_NAME, A.GENDER, COUNT(A.GENDER) AS NUM_ROLES
FROM MOVIE AS M
INNER JOIN CASTING AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR AS A ON C.ACTORNO = A.ACTORNO
GROUP BY M.TITLE, M.RELYEAR, A.GENDER
HAVING M.RELYEAR = 2001
AND COUNT(A.GENDER) <= 2
ORDER BY M.TITLE, A.GENDER DESC
;
SELECT '104153018' as studentid, M.TITLE AS MOVIE_NAME, A.GENDER, COUNT(A.GENDER) AS NUM_ROLES
FROM MOVIE AS M
INNER JOIN CASTING AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR AS A ON C.ACTORNO = A.ACTORNO
GROUP BY M.TITLE, M.RELYEAR, A.GENDER
HAVING M.RELYEAR = 2001
EXCEPT
SELECT '104153018' as studentid, M.TITLE AS MOVIE_NAME, A.GENDER, COUNT(A.GENDER) AS NUM_ROLES
FROM MOVIE AS M
INNER JOIN CASTING AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR AS A ON C.ACTORNO = A.ACTORNO
GROUP BY M.TITLE, M.RELYEAR, A.GENDER
HAVING M.RELYEAR = 2001
AND COUNT(A.GENDER) > 2
ORDER BY M.TITLE, A.GENDER DESC
;

SELECT M.TITLE, A.FULLNAME, C.COLOURNAME, R.SHORTDESC
FROM CASTING AS CA
INNER JOIN MOVIE AS M ON CA.MOVIENO = M.MOVIENO
INNER JOIN ACTOR AS A ON CA.ACTORNO = A.ACTORNO
INNER JOIN RATING AS R ON M.RATINGCODE = R.RATINGCODE
INNER JOIN COLOURTYPE AS C ON M.COLOURCODE = C.COLOURCODE
-- WHERE CA.CASTID IS NOT NULL
-- EXCEPT
-- INTERSECT
-- SELECT CA.CASTID
-- FROM CASTING AS CA
;

SELECT A.FULLNAME, COUNT(C.CASTID)
FROM ACTOR AS A 
LEFT JOIN CASTING AS C ON A.ACTORNO = C.ACTORNO
GROUP BY A.FULLNAME
-- HAVING COUNT(C.CASTID) = 0
;

SELECT A.FULLNAME, COUNT(C.CASTID)
FROM CASTING AS C
RIGHT JOIN ACTOR AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME
-- HAVING COUNT(C.CASTID) = 0
;

SELECT A.FULLNAME
FROM ACTOR AS A
FULL OUTER JOIN MOVIE ON 
;