use kayhoweDB;

-- SELECT TOP(10) MOVIENO, TITLE, RELYEAR, RUNTIME, RATINGCODE, COLOURCODE, TMDB_SCORE, TMDB_VOTES, TMDB_ID
-- FROM MOVIE3018;

SELECT TOP(5) *
FROM MOVIE3018
WHERE RUNTIME > (SELECT AVG(RUNTIME) FROM MOVIE3018)
;

SELECT *
FROM MOVIE3018
WHERE RUNTIME = (SELECT MAX(RUNTIME) FROM MOVIE3018)
;

SELECT M.TITLE, M.RELYEAR, A.FULLNAME, A.BIRTHCOUNTRY
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
WHERE A.BIRTHCOUNTRY IN (SELECT A.BIRTHCOUNTRY FROM ACTOR3018 WHERE A.BIRTHCOUNTRY = 'AUSTRALIA')
OR A.BIRTHCOUNTRY IN (SELECT A.BIRTHCOUNTRY FROM ACTOR3018 WHERE A.BIRTHCOUNTRY = 'ENGLAND')
;

SELECT RATINGCODE, AVG(RUNTIME) AS AVERAGE_LENGTH
FROM MOVIE3018
GROUP BY RATINGCODE
HAVING AVG(RUNTIME) > (SELECT AVG(RUNTIME) FROM MOVIE3018)
;

SELECT A.FULLNAME, COUNT(M.MOVIENO)
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO

;

SELECT A.FULLNAME, COUNT(M.TITLE) AS MOVIE_PROWESS
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME
ORDER BY FULLNAME ASC
;

SELECT A.FULLNAME, 'LIMITED' AS MOVIE_PROWESS
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME
HAVING COUNT(M.TITLE) < 4
UNION
SELECT A.FULLNAME, 'PROLIFIC' AS MOVIE_PROWESS
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME
HAVING COUNT(M.TITLE) >= 9
UNION
SELECT A.FULLNAME, 'SIGNIFICANT' AS MOVIE_PROWESS
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME
HAVING COUNT(M.TITLE) BETWEEN 4 AND 8
ORDER BY FULLNAME ASC
;

INSERT INTO COLOURTYPE3018 (colourcode, colourname) 
VALUES ('X', 'Black & White Movie');

SELECT *
FROM COLOURTYPE3018;

SELECT SHORTDESC
FROM RATING3018
UNION ALL
SELECT COLOURNAME
FROM COLOURTYPE3018
;

DELETE FROM COLOURTYPE3018 WHERE COLOURCODE = 'X';

SELECT *
FROM MOVIE3018
WHERE RATINGCODE = 'MA'
INTERSECT
SELECT *
FROM MOVIE3018
WHERE RELYEAR BETWEEN 2000 AND 2010
ORDER BY TITLE, RELYEAR ASC
;

SELECT *
FROM MOVIE3018
WHERE RELYEAR BETWEEN 2000 AND 2010
EXCEPT
SELECT *
FROM MOVIE3018
WHERE RELYEAR BETWEEN 2003 AND 2007
ORDER BY TITLE, RELYEAR ASC
; 