use kayhoweDB;

-- SELECT TOP(10) MOVIENO, TITLE, RELYEAR, RUNTIME, RATINGCODE, COLOURCODE, TMDB_SCORE, TMDB_VOTES, TMDB_ID
-- FROM MOVIE3018;

SELECT COUNT(MOVIENO) AS NO_OF_MOVIES
FROM MOVIE3018
;

SELECT COUNT(RATINGCODE) AS NO_OF_MOVIES
FROM MOVIE3018
HAVING COUNT(RATINGCODE) IS NOT NULL
;

SELECT RELYEAR AS RELEASE_YEAR, COUNT(MOVIENO) AS NUM_MOVIES
FROM MOVIE3018
GROUP BY RELYEAR
;

SELECT RELYEAR AS RELEASE_YEAR, COUNT(MOVIENO) AS NUM_MOVIES
FROM MOVIE3018
WHERE RELYEAR BETWEEN 2000 AND 2009
GROUP BY RELYEAR
;

SELECT RELYEAR AS RELEASE_YEAR, RATINGCODE AS RATING_CODE, MAX(RUNTIME) AS LENGTH_OF_LONGEST_MOVIE
FROM MOVIE3018
GROUP BY RATINGCODE, RELYEAR
ORDER BY RELYEAR ASC
;

SELECT A.FULLNAME, M.RATINGCODE, COUNT(M.RATINGCODE)
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME, M.RATINGCODE
ORDER BY FULLNAME ASC
;

SELECT A.FULLNAME, M.RATINGCODE, COUNT(M.RATINGCODE) AS NO_OF_MOVIES
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
WHERE M.RELYEAR BETWEEN 1990 AND 2010
GROUP BY A.FULLNAME, M.RATINGCODE
ORDER BY FULLNAME ASC
;

SELECT A.FULLNAME, M.RATINGCODE, COUNT(M.RATINGCODE) AS NO_OF_MOVIES
FROM MOVIE3018 AS M
INNER JOIN CASTING3018 AS C ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR3018 AS A ON C.ACTORNO = A.ACTORNO
WHERE M.RELYEAR BETWEEN 1990 AND 2010
GROUP BY A.FULLNAME, M.RATINGCODE
HAVING COUNT(M.RATINGCODE) >= 3
ORDER BY FULLNAME ASC
;

